### ISSUE TITLE
Failed watching pipe status -l 

### ISSUE THREAD

**Issue by bigspawn** [profclems/glab#325]
**Description**
```bash
» glab pipe status -l                                  
(running) • less than a minute ago      build           build

https://gitlab.......
SHA: ba5954.....
Pipeline State: running
panic: send on closed channel

goroutine 1 [running]:
github.com/gosuri/uilive.(*Writer).Stop(...)
        /home/runner/go/pkg/mod/github.com/gosuri/uilive@v0.0.4/writer.go:119
github.com/profclems/glab/commands/pipeline/status.NewCmdStatus.func1(0xc00042db80, 0xc00033cfe0, 0x0, 0x1, 0x0, 0x0)
        /home/runner/work/glab/glab/commands/pipeline/status/pipeline_status.go:133 +0xb92
github.com/spf13/cobra.(*Command).execute(0xc00042db80, 0xc00033cfd0, 0x1, 0x1, 0xc00042db80, 0xc00033cfd0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004e0dc0, 0xc000128050, 0x3, 0x3)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
main.main()
        /home/runner/work/glab/glab/cmd/glab/main.go:114 +0x712

```

**Your Environment**

* Version used: 1.11.1 
* Operating System and version: macOS 11.0.1 (20B29)

**Comment by profclems** [comment]
Sorry for having this issue. Run `glab pipe ci view` and see if you encounter any errors

**Comment by bigspawn** [comment]
When pipeline already started in gitlab server `glab pipe ci view` works well but for the first time when pipeline pending it failed with error
```bash
» glab pipe ci view
2020/11/20 16:21:33 runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc00041a0e0, 0x191c240, 0x21e2680)
	/opt/hostedtoolcache/go/1.14.10/x64/src/runtime/debug/stack.go:24 +0x9d
github.com/profclems/glab/commands/pipeline/ci/view.recoverPanic(0xc00041a0e0)
	/home/runner/work/glab/glab/commands/pipeline/ci/view/pipeline_ci_view.go:538 +0x65
panic(0x191c240, 0x21e2680)
	/opt/hostedtoolcache/go/1.14.10/x64/src/runtime/panic.go:969 +0x166
github.com/profclems/glab/commands/pipeline/ci/view.NewCmdView.func1(0xc0004c9080, 0x2230328, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/glab/glab/commands/pipeline/ci/view/pipeline_ci_view.go:96 +0x46d
github.com/spf13/cobra.(*Command).execute(0xc0004c9080, 0x2230328, 0x0, 0x0, 0xc0004c9080, 0x2230328)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000021080, 0xc0000bc050, 0x3, 0x3)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
main.main()
	/home/runner/work/glab/glab/cmd/glab/main.go:114 +0x712
```

**Comment by bigspawn** [comment]
seems that I can use `glab pipeline status --live` command instead of the old variant with `glab pipe status -l`

**Comment by zemzale** [comment]
About the panic in `glab pipe ci view` it seems that the panic is caused by trying to access `commit.LastPipeline.ID` [here](https://github.com/profclems/glab/blob/trunk/commands/pipeline/ci/view/pipeline_ci_view.go#L96).

I was able to reproduce this by creating an empty repo without any pipelines and then running `gitlab ci view`.
The API returned empty `last_pipeline` field and crashed
```json
{
    "id": "a08de9739df74848bfade011ba2f688ad064448e",
    "short_id": "a08de973",
    "created_at": "2020-11-20T14:17:18.000+00:00",
    "parent_ids": [],
    "title": "Update README.md",
    "message": "Update README.md",
    "author_name": "Alberts Zemzale",
    "author_email": "alberts.zemzale@gmail.com",
    "authored_date": "2020-11-20T14:17:18.000+00:00",
    "committer_name": "Alberts Zemzale",
    "committer_email": "alberts.zemzale@gmail.com",
    "committed_date": "2020-11-20T14:17:18.000+00:00",
    "web_url": "https://gitlab.com/zemzale/test/-/commit/a08de9739df74848bfade011ba2f688ad064448e",
    "stats": {
        "additions": 2,
        "deletions": 0,
        "total": 2
    },
    "status": null,
    "project_id": 22589168,
    "last_pipeline": null
}
```

I also was able to reproduce the error of the `glab pipe status -l` command. Seems like that is happening right before the pipeline is created. 
Steps to reproduce :
1. `glab pipe status -l`
2. retry 
3. instantly try to view logs and it will fail with panic

**Comment by nigel4321** [comment]
Not sure if this is related, though when I run 
`glab  pipeline status -l`

The response is : 
`GET https://gitlab..../api/v4/projects/tools/templates/pipelines: 400 {error: order_by does not have a valid value}`
Adding the above URL in the my browser's window gives me a 404.

`glab pipe ci view` works fine for me on the same project.

This is using hosted CE gitlab.

**Comment by profclems** [comment]
@nigel4321 I'm not really sure what might have caused it. The GitLab API changes. 
What version of GitLab CE are you using?
What version of `glab` are you using?

**Comment by nigel4321** [comment]
@profclems 
Tried with gitlab 11.11 and 12.10
glab 1.11.1

The list pipelines call (if that's what's happening there) looks like it was added in gitlab 8.11 : 
https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines

**Comment by zemzale** [comment]
We use `order_by:updated_at` with `glab pipeline status` here:
https://github.com/profclems/glab/blob/48d09dfd41b0357f801a4454fc6dd0d8fff6323e/commands/pipeline/status/pipeline_status.go#L56
It makes sense that there is an error with GitLab 11.11 since it wasn't there yet https://docs.gitlab.com/11.11/ee/api/pipelines.html#list-project-pipelines, but it should work with Gitlab 12.10 https://docs.gitlab.com/12.10/ee/api/pipelines.html#list-project-pipelines
Seems like the issue that @nigel4321 is having is not connected with the panic in the first encountered issue.

**Comment by profclems** [comment]
If I'm not mistaken, this should be resolved by #336 ([v1.12.0](https://github.com/profclems/glab/releases/v1.12.0))

/cc: @zemzale

**Comment by zemzale** [comment]
@profclems We actually have not fixed this yet. #336 fixed the issue with panic in `glab pipe ci view`, but not `glab pipeline status -l`. This is a different panic that happens when the pipeline is still pending and we try to view the status. I am looking into it right now so we can close this issue for good.
